#!/usr/bin/env bash

# Check if configuration is present
if [ ! -f settings.conf ]; then
    echo "settings.conf not found"
    exit 1
fi
# Source configuration
. settings.conf

# Follow the journal, reading every line
journalctl -f | \
while read line ; do
    if [ -z "$exceptions" ]
    then
        # Grep the line for the pattern
        grep -q -E "$pattern" <<< "$line"
    else
        # Grep the line for the pattern and filter out exceptions
        grep -E "$pattern" <<< "$line" | grep -q -E -v "$exceptions"
    fi
    # Check grep exit status
    if [ $? = 0 ]
    then
        curl -s -X POST "https://api.telegram.org/bot${token}/sendMessage" \
        -d chat_id="$chat_id" -d text="$line" > /dev/null
    fi
done
