#!/usr/bin/env bash

# Source configuration. Yes it's insecure. To be improved.
. settings.conf

# Follow the journal, reading every line
journalctl -f | \
while read line ; do
    # Grep the line for the pattern
    grep -q -E "$pattern" <<< "$line"
    # Check grep exit status
    if [ $? = 0 ]
    then
        curl -s -X POST "https://api.telegram.org/bot${token}/sendMessage" \
        -d chat_id="$chat_id" -d text="$line" > /dev/null
    fi
done
